Somewhere there is still a race condition:

INFO: monitoring03: Running manifest and explorers for __file/etc/yum.repos.d/epel.repo
^C^CTraceback (most recent call last):
  File "./bin/cdist", line 204, in <module>
    import logging
  File "/usr/lib/python3.2/logging/__init__.py", line 27, in <module>
    from string import Template
  File "/usr/lib/python3.2/string.py", line 178, in <module>
    class Formatter:
  File "/usr/lib/python3.2/string.py", line 179, in Formatter
    def format(self, format_string, *args, **kwargs):
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bin/cdist", line 232, in <module>
    sys.exit(0)
NameError: name 'sys' is not defined
^C^CFatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "/usr/lib/python3.2/encodings/latin_1.py", line 8, in <module>
    """
KeyboardInterrupt
^C%                                                                                                                   [12:19] brief:cdist%
